### ISSUE TITLE
How to increase lighting

### ISSUE THREAD

**Issue by 102757017** [Android-for-Python/c4k_qr_example#1]
sometimes，it is too dark. how can i turn on the flash lighting when scan a QR code.
I tried to use "qrreader.flash()",but it did not work.

**Comment by RobertFlatt** [comment]
https://github.com/Android-for-Python/camera4kivy#flash

Its a state machine, so you are presumably just turning it from auto to off. Neither of which are what you want. 
I have no idea if it will turn on in this case, but you could try it.

**Comment by 102757017** [comment]
> https://github.com/Android-for-Python/camera4kivy#flash
> 
> Its a state machine, so you are presumably just turning it from auto to off. Neither of which are what you want. I have no idea if it will turn on in this case, but you could try it.

Infact,I have created a button on the layout which could run the flash function, but no matter how many times I pressed the button,It didn't work at all. 
In that way i have tried all the three states. So i think it is not that reason case this matter.

I even tried to init the camera in the follow way,but it did turn on the flash light either.
qrreader.connect_camera(enable_analyze_pixels = True,default_flash = 'on')

I wonder whether other permissions are required besides the camera permission to turn on the flash light on android
Can you give some advice to solve this problem.

**Comment by RobertFlatt** [comment]
Sorry, I don't know about this.

**Comment by 102757017** [comment]
After researching the sourc code of cameraX,I figured it out.

I can use the code below to contrl the flash light,Although it is not an elegant way.

 

camera=self.ids.qrreader.preview._camera.camera

cameraControl = camera.getCameraControl()

cameraInfo = camera.getCameraInfo()

cameraControl.enableTorch(True) #turn on the flash light

cameraControl.enableTorch(False) #turn off the flash light
